# Generated by Django 4.0.1 on 2022-01-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_empresa_instagram_alter_empresa_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='Codigo_da_Empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_da_empresa', to='marketing.empresa'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='Valor_do_Anuncio',
            field=models.FloatField(),
        ),
    ]
