# Generated by Django 4.0.1 on 2022-01-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_anuncio_codigo_da_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='Valor_do_Anuncio',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
